// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`should test prisma client and postgres should verify that the prisma client automatically recovers after an interrupted db server connection 1`] = `
[Error: 
Invalid \`prisma.user.findMany()\` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })]
`;
